### ISSUE TITLE
wifibox-0.6.2 depends on package: bhyve+>0 - not found

### ISSUE THREAD

**Issue by Corazone777** [pgj/freebsd-wifibox-port#1]
As the title says i tried to install wifibox and get the error.

There is no said package in /usr/ports/sysutils

BSD 13.0 Release amd64

**Comment by pgj** [comment]
That is interesting.  There must be a `sysutils/bhyve+` port available in the FreeBSD ports tree, it has been added to it a while ago ([September 2021](https://www.freshports.org/sysutils/bhyve+)).  Is this a fresh FreeBSD installation?  Note that you will have to [update your ports tree via e.g. `portsnap`](https://docs.freebsd.org/en/books/handbook/ports/#ports-using).

But you may also choose to simply install the `bhyve+` package itself via `pkg`:

```console
# pkg install sysutils/bhyve+
```

**Comment by pgj** [comment]
By the way, there is no need to use this port, installing the `net/wifibox` package via `pkg` will suffice.

**Comment by pgj** [comment]
I updated the `README` file to provide instructions for situations like yours.

**Comment by Corazone777** [comment]
Thank you a lot.
